name: flutter_widgets
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  sizer: ^2.0.15
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

