import 'package:get/get.dart';

class HomeController extends GetxController {
  var dataList = [
    "About Dialog",
    "About List Tile",
    "Absorb Pointer",
    "Alert Dialog",
    "Align",
    "Animated Align",
    "Animated Builder",
    "Animated Container",
    "Animated Cross Fade",
    "Animated Default Text Style",
    "Animated Icon",
    "Animated List",
    "Animated Modal Barrier",
    "Animated Opacity",
    "Animated Padding",
    "Animated Physical Model",
    "Animated Positioned",
    "Animated Rotation",
    "Animated Size",
    "Animated Switcher",
    "App Bar",
    "Aspect Ratio",
    "Auto Complete",
    "Backdrop Filter",
    "Banner",
    "Baseline",
    "Block Semantics",
    "Bottom Navigation Bar",
    "Bottom Sheet",
    "Builder",
    "Card",
    "Center",
    "Checkbox",
    "Checkbox List Tile",
    "Chip",
    "Choice Chip",
    "Circle Avatar",
    "Circular Progress Indicator",
    "Clip Oval",
    "Clip Path",
    "ClipRRect",
    "ClipRect",
    "Close Button",
    "Color Filtered",
    "Colored Box",
    "Column",
    "Constrained Box",
    "Container",
    "Cupertino Context Menu",
    "Cupertino Sliding Segmented Control",
    "Cupertino Widgets (5)",
    "Cupertino Widgets (6)",
    "Cupertino Widgets (9)",
    "Custom Paint",
    "Custom Scroll View",
    "Data Cell",
    "Data Column",
    "Data Row",
    "Data Table",
    "Date Picker",
    "Date Range Picker",
    "Decorated Box",
    "Decorated Box Transition",
    "Default Text Style",
    "Dismissible",
    "Divider",
    "Drag Target",
    "Draggable Scrollable",
    "Draggable",
    "Drawer Header",
    "Drawer",
    "Dropdown Button",
    "Elevated Button",
    "Error Details",
    "Error Widget",
    "Expand Icon",
    "Expanded",
    "Expansion Panel",
    "Expansion Panel List",
    "Expansion Tile",
    "Fade In Image",
    "Fade Transition",
    "Filter Chip",
    "Fitted Box",
    "Flexible",
    "Floating Action Button",
    "Flow",
    "Flutter Logo",
    "Form",
    "Fractional Translation",
    "Fractionally Sized Box",
    "Future Builder",
    "Gesture Detector",
    "Grid Paper",
    "Grid Tile Bar",
    "Grid Tile",
    "Grid View",
    "Hero",
    "Icon",
    "Icon Button",
    "Ignore Pointer",
    "Image",
    "Indexed Stack",
    "Inkwell",
    "Input Chip",
    "Interactive Viewer",
    "Layout Builder",
    "Limited Box",
    "Linear Progress Indicator",
    "List Tile",
    "List View",
    "List Wheel Scroll View",
    "Listener",
    "Long Press Draggable",
    "Material App",
    "Material Banner",
    "Material Button",
    "Merge Semantics",
    "Modal Barrier",
    "Mouse Region",
    "Navigation Bar",
    "Notification Listener",
    "Offstage",
    "Opacity",
    "Orientation Builder",
    "Outlined Button",
    "Overflow Bar",
    "Overflow Box",
    "Padding",
    "Page View",
    "Physical Modal",
    "Physical Shape",
    "Placeholder",
    "Platform Menu Bar",
    "Popup Menu Button",
    "Positioned Transition",
    "Positioned",
    "Preferred Size",
    "Radio",
    "Radio List Tile",
    "Range Slider",
    "Raw Autocomplete",
    "Raw Chip",
    "Refresh Indicator",
    "Reorderable List View",
    "Rich Text",
    "Rotated Box",
    "Rotation Transition",
    "Row",
    "Safe Area",
    "Scaffold",
    "Scale Transition",
    "Scrollbar",
    "Selectable Text",
    "Semantics",
    "Shader Mask",
    "Shortcuts",
    "Simple Dialog",
    "Single Child Scroll View",
    "Size Transition",
    "Sized Box",
    "Sized Overflow Box",
    "Slide Transition",
    "Slider",
    "Sliver Widgets (7)",
    "Snack Bar",
    "Spacer",
    "Stack",
    "Stepper",
    "Stream Builder",
    "Switch List Tile",
    "Switch",
    "System Mouse Cursors",
    "Tab Bar",
    "Tab Page Selector",
    "Table",
    "Text",
    "Text Button",
    "Text Field",
    "Text Form Field",
    "Text Span",
    "Theme Data",
    "Time Picker",
    "Toggle Buttons",
    "Tooltip",
    "Transform",
    "Tween Animation Builder",
    "Value Listenable Builder",
    "Vertical Divider",
    "Visibility",
    "Will Pop Scope",
    "Wrap",
  ];

}
